### PR TITLE
fix nil check errors (#21)

### PR DESCRIPTION
**Pull request by RamanaReddy0M**

### CODE REVIEW

**Review by tarunKoyalwar — CHANGES_REQUESTED** [review]
- requesting changes since this does not fix the issue refer: https://github.com/projectdiscovery/nuclei/pull/3405
- @RamanaReddy0M  we should validate latest commit with upstream pr to check if bug/panic was really fixed

**Review by tarunKoyalwar — APPROVED** [review]
since panic has been resolved https://github.com/projectdiscovery/nuclei/actions/runs/4388421122/jobs/7684897896

**Comment by tarunKoyalwar** [comment]
@ehsandeep , this requires creating new release after merge in [nuclei-publish-doc-fix]( https://github.com/projectdiscovery/nuclei/pull/3405) PR dstdocgen command is installed via commit hash instead of using `@latest` temporarily

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
@tarunKoyalwar new release published for this release, we can update nuclei PR to point the latest release.

**Pull request merged**
